import { hello } from './modules/_hello.js';
// import { initLazyLoad } from './modules/_lazyload';
import { burger } from './modules/_burger.js';
import { initSlider } from "./modules/_initSlider.js";
import {animationScroll} from "./modules/_animationScroll.js";
import {scrollHeader} from "./modules/_scrollHeader.js";
import { pressDawn } from "./modules/_pressDawn.js";
import { pressUp } from "./modules/_pressUp.js";
import { catalog } from "./modules/_catalog.js";
import { sendForm } from "./modules/_form.js";
import { modalImg } from "./modules/_modalImg.js";

hello();
// initLazyLoad();
burger();
initSlider();
animationScroll();
scrollHeader();
pressDawn();
pressUp();
catalog();
sendForm();
modalImg();
